"""Compute transferability baselines for single- and multi-modal embeddings.

This script consolidates several transferability metrics from the literature so
they can be evaluated on top of the feature files produced by the extraction
pipelines in this repository. Both single-modality (image only) checkpoints
generated by :mod:`extract_features.py` and multimodal CLIP-style checkpoints
produced by :mod:`multimodal_feature_extraction.py` are supported.

Metrics implemented
-------------------
* Gaussian Bhattacharyya Coefficient (GBC)
* Self-Distilled Fisher Discriminant Analysis (SFDA)
* TransRate
* EMMS (requires text backbones from Hugging Face)
* NCTI
* H-score

The implementation is largely adapted from the reference repositories linked in
``README.md`` and the snippet provided by the user. Minor adjustments were made
to integrate the metrics with PyTorch ``.pth`` feature dumps and to improve
numerical stability.

Example usage
-------------
Compute all metrics for a single-modality checkpoint::

    python transferability_baselines.py         single /path/to/features.pth         --manifest /path/to/manifest.csv --label-column subtype

Evaluate a multimodal feature file across all magnifications::

    python transferability_baselines.py         multi /path/to/multimodal_features.pth         --manifest /path/to/manifest.csv         --label-column subtype

Results are printed to stdout and can optionally be exported as JSON via
``--json``.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import warnings
from dataclasses import dataclass
from typing import Dict, Iterable, List, Mapping, MutableMapping, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
from scipy.stats import weightedtau

try:
    import torch
except ImportError as exc:  # pragma: no cover - torch is a runtime requirement
    raise SystemExit("transferability_baselines.py requires PyTorch to be installed") from exc


# ---------------------------------------------------------------------------
# Utility helpers
# ---------------------------------------------------------------------------


def _to_numpy(tensor: torch.Tensor) -> np.ndarray:
    return tensor.detach().cpu().numpy()


@dataclass
class FeatureBundle:
    embeddings: np.ndarray
    labels: Optional[np.ndarray]
    label_names: Optional[Dict[int, str]] = None
    metadata: Optional[Mapping[str, object]] = None


DEFAULT_GROUND_TRUTH: Dict[str, Dict[str, float]] = {
    "TCGA": {
        "plip": 0.59,
        "musk": 0.65,
        "conch": 0.58,
        "pathgen": 0.60,
    }
}


DEFAULT_DATASET_MODEL_PATHS: Dict[str, Dict[str, str]] = {
    "TCGA": {
        "plip": "/home/jovyan/work/tran_est/MUST/features/plip_features02.pth",
        "musk": "/home/jovyan/work/tran_est/MUST/features/musk_features02.pth",
        "conch": "/home/jovyan/work/tran_est/MUST/features/conch_features02.pth",
        "pathgen": "/home/jovyan/work/tran_est/MUST/features/pathgen_features02.pth",
    }
}


DEFAULT_SINGLE_GROUND_TRUTH: Dict[str, Dict[str, float]] = {
    "TCGA": {
        "uni": 0.4856,
        "conch": 0.4916,
        "giga": 0.5108,
        "phikon": 0.4675,
        "virchow": 0.4952,
    }
}


DEFAULT_SINGLE_DATASET_MODEL_PATHS: Dict[str, Dict[str, Dict[str, object]]] = {
    "TCGA": {
        "uni": {
            "train": "/home/jovyan/work/tran_est/MUST/features_unimodal/uni_train_features.pth",
            "eval": "/home/jovyan/work/tran_est/MUST/features_unimodal/uni_eval_features.pth",
            "msci": {
                "manifest": "/home/jovyan/work/tran_est/multires_txt02.csv",
                "region_column": "patch_id",
                "magnification_column": "patch_scale",
                "label_column": "label",
                "magnifications": [5, 10, 20, 40],
            },
        },
        "conch": {
            "train": "/home/jovyan/work/tran_est/MUST/features_unimodal/conch_train_features.pth",
            "eval": "/home/jovyan/work/tran_est/MUST/features_unimodal/conch_eval_features.pth",
            "msci": {
                "manifest": "/home/jovyan/work/tran_est/multires_txt02.csv",
                "region_column": "patch_id",
                "magnification_column": "patch_scale",
                "label_column": "label",
                "magnifications": [5, 10, 20, 40],
            },
        },
        "giga": {
            "train": "/home/jovyan/work/tran_est/MUST/features_unimodal/giga_train_features.pth",
            "eval": "/home/jovyan/work/tran_est/MUST/features_unimodal/giga_eval_features.pth",
            "msci": {
                "manifest": "/home/jovyan/work/tran_est/multires_txt02.csv",
                "region_column": "patch_id",
                "magnification_column": "patch_scale",
                "label_column": "label",
                "magnifications": [5, 10, 20, 40],
            },
        },
        "phikon": {
            "train": "/home/jovyan/work/tran_est/MUST/features_unimodal/phikon_train_features.pth",
            "eval": "/home/jovyan/work/tran_est/MUST/features_unimodal/phikon_eval_features.pth",
            "msci": {
                "manifest": "/home/jovyan/work/tran_est/multires_txt02.csv",
                "region_column": "patch_id",
                "magnification_column": "patch_scale",
                "label_column": "label",
                "magnifications": [5, 10, 20, 40],
            },
        },
        "virchow": {
            "train": "/home/jovyan/work/tran_est/MUST/features_unimodal/virchow_train_features.pth",
            "eval": "/home/jovyan/work/tran_est/MUST/features_unimodal/virchow_eval_features.pth",
            "msci": {
                "manifest": "/home/jovyan/work/tran_est/multires_txt02.csv",
                "region_column": "patch_id",
                "magnification_column": "patch_scale",
                "label_column": "label",
                "magnifications": [5, 10, 20, 40],
            },
        },
    }
}


# ---------------------------------------------------------------------------
# Metric implementations
# ---------------------------------------------------------------------------


def compute_bhattacharyya_distance(mu1: np.ndarray, mu2: np.ndarray, sigma1: np.ndarray, sigma2: np.ndarray) -> float:
    """Compute the Bhattacharyya distance between diagonal Gaussians."""

    avg_sigma = (sigma1 + sigma2) / 2.0
    first = np.sum((mu1 - mu2) ** 2 / avg_sigma) / 8.0
    second = np.sum(np.log(avg_sigma)) - 0.5 * (np.sum(np.log(sigma1)) + np.sum(np.log(sigma2)))
    return float(first + 0.5 * second)


def _per_class_stats(features: np.ndarray, labels: np.ndarray, spherical: bool) -> Dict[int, Dict[str, np.ndarray]]:
    stats: Dict[int, Dict[str, np.ndarray]] = {}
    for label in np.unique(labels):
        mask = labels == label
        feats = features[mask]
        mean = feats.mean(axis=0)
        var = np.maximum(feats.var(axis=0), 1e-4)
        if spherical:
            var = np.full_like(var, var.mean())
        stats[int(label)] = {"mean": mean, "var": var}
    return stats


def gbc_score(features: np.ndarray, labels: np.ndarray, gaussian_type: str = "diagonal") -> float:
    if gaussian_type not in {"diagonal", "spherical"}:
        raise ValueError("gaussian_type must be either 'diagonal' or 'spherical'")
    stats = _per_class_stats(features, labels, spherical=gaussian_type == "spherical")
    accum: List[float] = []
    for c1 in np.unique(labels):
        distances: List[float] = []
        for c2 in np.unique(labels):
            if c1 == c2:
                continue
            dist = compute_bhattacharyya_distance(
                stats[int(c1)]["mean"],
                stats[int(c2)]["mean"],
                stats[int(c1)]["var"],
                stats[int(c2)]["var"],
            )
            distances.append(math.exp(-dist))
        accum.append(np.sum(distances))
    return float(-np.sum(accum))


def _covariance(X: np.ndarray, shrinkage: float = -1.0) -> np.ndarray:
    emp = np.cov(np.asarray(X).T, bias=True)
    if shrinkage < 0:
        return emp
    n_features = emp.shape[0]
    mu = np.trace(emp) / n_features
    shrunk = (1.0 - shrinkage) * emp
    shrunk.flat[:: n_features + 1] += shrinkage * mu
    return shrunk


def _softmax(logits: np.ndarray) -> np.ndarray:
    shifted = logits - logits.max(axis=1, keepdims=True)
    exp = np.exp(shifted)
    return exp / exp.sum(axis=1, keepdims=True)


def _class_means(X: np.ndarray, y: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    classes, inv = np.unique(y, return_inverse=True)
    counts = np.bincount(inv)
    means = np.zeros((len(classes), X.shape[1]), dtype=X.dtype)
    np.add.at(means, inv, X)
    means /= counts[:, None]
    outer = np.zeros_like(means)
    for idx in range(len(classes)):
        outer[idx] = (np.sum(means, axis=0) - means[idx]) / max(1, len(classes) - 1)
    return means, outer


def _iterative_max_eigenvalue(matrix: np.ndarray, max_iterations: int = 5) -> float:
    rng = np.random.default_rng(42)
    vec = rng.standard_normal(matrix.shape[0])
    value = 0.0
    for _ in range(max_iterations):
        vec = matrix @ vec
        norm = np.linalg.norm(vec)
        if norm == 0:
            break
        vec /= norm
        value = float(vec @ (matrix @ vec))
    return value


class SFDA:
    def __init__(self, shrinkage: Optional[float] = None, priors: Optional[np.ndarray] = None, n_components: Optional[int] = None) -> None:
        self.shrinkage = shrinkage
        self.priors = priors
        self.n_components = n_components
        self.scalings_: Optional[np.ndarray] = None
        self.coef_: Optional[np.ndarray] = None
        self.intercept_: Optional[np.ndarray] = None
        self.means_: Optional[np.ndarray] = None
        self.priors_: Optional[np.ndarray] = None
        self.covariance_: Optional[np.ndarray] = None

    def _solve(self, X: np.ndarray, y: np.ndarray) -> None:
        classes, inv = np.unique(y, return_inverse=True)
        counts = np.bincount(inv)
        means = np.zeros((len(classes), X.shape[1]), dtype=X.dtype)
        np.add.at(means, inv, X)
        means /= counts[:, None]
        self.means_ = means

        cov = np.zeros((X.shape[1], X.shape[1]), dtype=X.dtype)
        for idx, cls in enumerate(classes):
            samples = X[y == cls]
            cov += self.priors_[idx] * _covariance(samples)
        self.covariance_ = cov

        Sw = cov
        if self.shrinkage is None:
            largest = _iterative_max_eigenvalue(Sw, max_iterations=5)
            shrinkage = max(math.exp(-5.0 * largest), 1e-10)
            self.shrinkage = shrinkage
        else:
            shrinkage = self.shrinkage

        St = _covariance(X, shrinkage=self.shrinkage)
        n_features = Sw.shape[0]
        mu = np.trace(Sw) / n_features
        shrunk = (1.0 - shrinkage) * Sw
        shrunk.flat[:: n_features + 1] += shrinkage * mu
        Sb = St - shrunk

        evals, evecs = np.linalg.eigh(np.linalg.pinv(shrunk) @ Sb)
        order = np.argsort(evals)[::-1]
        evecs = evecs[:, order]
        self.scalings_ = evecs
        self.coef_ = means @ evecs @ evecs.T
        self.intercept_ = -0.5 * np.diag(self.means_ @ self.coef_.T) + np.log(self.priors_)

    def fit(self, X: np.ndarray, y: np.ndarray) -> "SFDA":
        classes = np.unique(y)
        max_components = min(len(classes) - 1, X.shape[1])
        if self.n_components is not None and self.n_components > max_components:
            raise ValueError("n_components cannot exceed min(n_features, n_classes - 1)")
        self._max_components = max_components if self.n_components is None else self.n_components
        _, inv = np.unique(y, return_inverse=True)
        self.priors_ = np.bincount(inv) / len(y)
        self._solve(X, y)
        return self

    def transform(self, X: np.ndarray) -> np.ndarray:
        if self.scalings_ is None:
            raise RuntimeError("Model must be fit before calling transform")
        return (X @ self.scalings_)[:, : self._max_components]

    def predict_proba(self, X: np.ndarray) -> np.ndarray:
        if self.coef_ is None or self.intercept_ is None:
            raise RuntimeError("Model must be fit before calling predict_proba")
        scores = X @ self.coef_.T + self.intercept_
        return _softmax(scores)


def sfda_score(X: np.ndarray, y: np.ndarray) -> float:
    X = X.copy()
    model = SFDA()
    probs = model.fit(X, y).predict_proba(X)
    probs = _softmax(np.log(np.clip(probs, 1e-12, 1.0)))
    means, outer = _class_means(X, y)
    num_classes = len(np.unique(y))
    for cls in range(num_classes):
        idx = np.where(y == cls)[0]
        cls_prob = probs[idx, cls][:, None]
        X[idx] = cls_prob * X[idx] + (1.0 - cls_prob) * outer[cls]
    second = SFDA(shrinkage=model.shrinkage)
    probs = second.fit(X, y).predict_proba(X)
    indices = np.arange(len(y))
    score = np.sum(probs[indices, y]) / len(y)
    return float(score)


def coding_rate(Z: np.ndarray, eps: float = 1e-4) -> float:
    n, d = Z.shape
    identity = np.eye(d)
    _, rate = np.linalg.slogdet(identity + (1.0 / (n * eps)) * (Z.T @ Z))
    return 0.5 * rate


def transrate_score(Z: np.ndarray, y: np.ndarray, eps: float = 1e-4) -> float:
    Z = Z - Z.mean(axis=0, keepdims=True)
    total = coding_rate(Z, eps)
    per_class = 0.0
    for cls in np.unique(y):
        cls_feats = Z[y == cls]
        per_class += coding_rate(cls_feats, eps)
    return float(total - per_class / len(np.unique(y)))


def sparsemax(z: np.ndarray) -> np.ndarray:
    z_sorted = np.sort(z, axis=1)[:, ::-1]
    z_cumsum = np.cumsum(z_sorted, axis=1)
    k = np.arange(1, z.shape[1] + 1)
    z_check = 1 + k * z_sorted > z_cumsum
    k_z = z.shape[1] - np.argmax(z_check[:, ::-1], axis=1)
    tau_sum = z_cumsum[np.arange(z.shape[0]), k_z - 1]
    tau = ((tau_sum - 1) / k_z).reshape(-1, 1)
    return np.maximum(0.0, z - tau)


def emms_score(Z: np.ndarray, label_embeddings: np.ndarray) -> float:
    if label_embeddings.ndim != 2:
        raise ValueError("label_embeddings must be 2-D [num_labels, embed_dim]")
    num_labels, embed_dim = label_embeddings.shape
    N = Z.shape[0]
    expanded = np.repeat(label_embeddings[None, :, :], N, axis=0)
    expanded = np.transpose(expanded, (0, 2, 1))  # [N, embed_dim, num_labels]
    X = Z.copy()
    Y = expanded.copy()

    for i in range(num_labels):
        y_mean = Y[:, :, i].mean(axis=0)
        y_std = Y[:, :, i].std(axis=0)
        Y[:, :, i] = (Y[:, :, i] - y_mean) / (y_std + 1e-8)
    X = (X - X.mean(axis=0, keepdims=True)) / (X.std(axis=0, keepdims=True) + 1e-8)

    lam = np.full((num_labels, 1), 1.0 / num_labels)
    b = (Y @ lam).reshape(N, embed_dim)
    w, _, _, _ = np.linalg.lstsq(X, b, rcond=None)
    for _ in range(1):
        a = Y.reshape(N * embed_dim, num_labels)
        target = (X @ w).reshape(N * embed_dim)
        lam = np.linalg.lstsq(a, target, rcond=None)[0].reshape(1, num_labels)
        lam = sparsemax(lam)
        lam = lam.reshape(num_labels, 1)
        b = (Y @ lam).reshape(N, embed_dim)
    prediction = X @ w
    residual = np.sum((prediction - b) ** 2) / (N * embed_dim)
    return float(-residual)


def ncti_score(X: np.ndarray, y: np.ndarray) -> Tuple[float, float, float]:
    from sklearn.decomposition import PCA
    from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

    C = len(np.unique(y))
    pca = PCA(n_components=min(64, X.shape[1]))
    X_pca = pca.fit_transform(X)
    shrink = max(math.exp(-pca.explained_variance_[:32].sum()), 1e-10)
    if shrink == 1e-10:
        lda = LinearDiscriminantAnalysis(solver="svd")
    else:
        lda = LinearDiscriminantAnalysis(solver="eigen", shrinkage=float(shrink))
    low = lda.fit_transform(X_pca, y)
    low -= low.mean(axis=0, keepdims=True)
    seli = np.linalg.norm(low, ord="nuc")
    probs = lda.predict_proba(X_pca)
    ncc = float(np.sum(probs[np.arange(X.shape[0]), y]) / X.shape[0])
    vc = 0.0
    for cls in np.unique(y):
        cls_probs = probs[y == cls]
        vc += np.linalg.norm(cls_probs, ord="nuc")
    vc = math.log(vc)
    return float(seli), float(ncc), float(vc)


def h_score(X: np.ndarray, y: np.ndarray) -> float:
    def cov(mat: np.ndarray) -> np.ndarray:
        centered = mat - mat.mean(axis=0, keepdims=True)
        return centered.T @ centered / max(1, mat.shape[0] - 1)

    cov_x = cov(X)
    classes = np.unique(y)
    g = np.zeros_like(X)
    for cls in classes:
        mean = X[y == cls].mean(axis=0)
        g[y == cls] = mean
    cov_g = cov(g)
    score = np.trace(np.linalg.pinv(cov_x, rcond=1e-12) @ cov_g)
    return float(score)


# ---------------------------------------------------------------------------
# Loading helpers
# ---------------------------------------------------------------------------


def _load_manifest(manifest: Optional[str]) -> Optional[pd.DataFrame]:
    if manifest is None:
        return None
    if not os.path.exists(manifest):
        raise FileNotFoundError(f"Manifest not found: {manifest}")
    return pd.read_csv(manifest)


def _build_label_map(labels: Sequence[str]) -> Tuple[np.ndarray, Dict[int, str]]:
    mapping: Dict[str, int] = {}
    numeric: List[int] = []
    for label in labels:
        key = str(label)
        if key not in mapping:
            mapping[key] = len(mapping)
        numeric.append(mapping[key])
    reverse = {idx: lab for lab, idx in mapping.items()}
    return np.asarray(numeric, dtype=np.int64), reverse


def load_single_features(path: str, manifest: Optional[str], label_column: Optional[str]) -> FeatureBundle:
    payload: MutableMapping[str, object] = torch.load(path, map_location="cpu")
    if "embeddings" not in payload:
        raise KeyError("Expected 'embeddings' in feature file")
    embeddings = _to_numpy(payload["embeddings"])
    labels_tensor = payload.get("labels")
    labels: Optional[np.ndarray]
    label_names: Optional[Dict[int, str]] = None

    manifest_df = _load_manifest(manifest)
    if labels_tensor is not None and isinstance(labels_tensor, torch.Tensor) and labels_tensor.numel() == embeddings.shape[0]:
        labels = labels_tensor.detach().cpu().numpy().astype(np.int64)
        if manifest_df is not None and label_column and "row_indices" in payload:
            indices = np.asarray(payload["row_indices"], dtype=np.int64)
            subset = manifest_df.iloc[indices]
            label_series = subset[label_column].astype(str).tolist()
            numeric, reverse = _build_label_map(label_series)
            if numeric.shape[0] == labels.shape[0]:
                labels = numeric
                label_names = reverse
    elif manifest_df is not None and label_column:
        if "row_indices" not in payload:
            raise ValueError("Feature file is missing 'row_indices'; provide labels directly or regenerate features")
        indices = np.asarray(payload["row_indices"], dtype=np.int64)
        subset = manifest_df.iloc[indices]
        numeric, reverse = _build_label_map(subset[label_column].astype(str))
        labels = numeric
        label_names = reverse
    else:
        labels = None

    return FeatureBundle(embeddings=embeddings, labels=labels, label_names=label_names, metadata=payload)


def load_multimodal_features(
    path: str,
    manifest: Optional[str],
    *,
    label_column: Optional[str],
    region_column: str,
    magnification_column: str,
) -> Tuple[Dict[int, FeatureBundle], FeatureBundle]:
    payload: MutableMapping[str, object] = torch.load(path, map_location="cpu")
    if "image_embeddings" not in payload or "text_embeddings" not in payload:
        raise KeyError("Expected 'image_embeddings' and 'text_embeddings' in multimodal feature file")

    image_embeddings: Dict[int, torch.Tensor] = {}
    for key, value in payload["image_embeddings"].items():
        image_embeddings[int(key)] = value
    magnifications = sorted(image_embeddings.keys())

    metadata = payload.get("metadata", {})
    region_ids: List[str] = list(metadata.get("region_ids", []))
    csv_mapping: Dict[str, Sequence[str]] = metadata.get("csv_region_mapping", {})

    manifest_df = _load_manifest(manifest)
    labels: Optional[np.ndarray] = None
    label_names: Optional[Dict[int, str]] = None
    if manifest_df is not None and label_column:
        lookup: Dict[str, str] = {}
        for _, row in manifest_df.iterrows():
            lookup[str(row[region_column])] = str(row[label_column])
        resolved: List[str] = []
        for region in region_ids:
            candidates = csv_mapping.get(region, [region])
            label = None
            for candidate in candidates:
                if candidate in lookup:
                    label = lookup[candidate]
                    break
            if label is None:
                warnings.warn(f"Unable to resolve label for region '{region}' from manifest; assigning placeholder")
                label = "unknown"
            resolved.append(label)
        labels, label_names = _build_label_map(resolved)

    bundles: Dict[int, FeatureBundle] = {}
    for mag in magnifications:
        embeddings = _to_numpy(image_embeddings[mag])
        bundles[mag] = FeatureBundle(embeddings=embeddings, labels=labels, label_names=label_names, metadata=metadata)

    text_bundle = FeatureBundle(
        embeddings=_to_numpy(payload["text_embeddings"]),
        labels=labels,
        label_names=label_names,
        metadata=metadata,
    )
    return bundles, text_bundle


# ---------------------------------------------------------------------------
# Metric evaluation
# ---------------------------------------------------------------------------


def evaluate_metrics(bundle: FeatureBundle, metrics: Sequence[str], *, gaussian_type: str, emms_backend: Optional[str], emms_model: Optional[str]) -> Dict[str, object]:
    if bundle.embeddings.size == 0:
        raise ValueError("No embeddings found in the feature file")
    labels = bundle.labels
    results: Dict[str, object] = {}

    feature_matrix = bundle.embeddings.astype(np.float64)
    label_array = labels.astype(np.int64) if labels is not None else None

    for metric in metrics:
        if metric == "gbc":
            if label_array is None:
                warnings.warn("Skipping GBC because labels are unavailable")
                continue
            results["gbc"] = gbc_score(feature_matrix, label_array, gaussian_type=gaussian_type)
        elif metric == "sfda":
            if label_array is None:
                warnings.warn("Skipping SFDA because labels are unavailable")
                continue
            results["sfda"] = sfda_score(feature_matrix, label_array)
        elif metric == "transrate":
            if label_array is None:
                warnings.warn("Skipping TransRate because labels are unavailable")
                continue
            results["transrate"] = transrate_score(feature_matrix, label_array)
        elif metric == "emms":
            if bundle.label_names is None:
                warnings.warn("Skipping EMMS because label names are unavailable")
                continue
            embeddings = _resolve_label_embeddings(bundle.label_names, backend=emms_backend, model_name=emms_model)
            results["emms"] = emms_score(feature_matrix, embeddings)
        elif metric == "ncti":
            if label_array is None:
                warnings.warn("Skipping NCTI because labels are unavailable")
                continue
            seli, ncc, vc = ncti_score(feature_matrix, label_array)
            results["ncti_seli"] = seli
            results["ncti_ncc"] = ncc
            results["ncti_vc"] = vc
        elif metric == "hscore":
            if label_array is None:
                warnings.warn("Skipping H-score because labels are unavailable")
                continue
            results["h_score"] = h_score(feature_matrix, label_array)
        else:
            raise ValueError(f"Unknown metric '{metric}'")
    return {key: float(value) for key, value in results.items()}


def _aggregate_metric_dict(outputs: Mapping[str, Mapping[str, float]]) -> Dict[str, float]:
    totals: Dict[str, float] = {}
    counts: Dict[str, int] = {}
    for metric_dict in outputs.values():
        for metric, value in metric_dict.items():
            totals[metric] = totals.get(metric, 0.0) + float(value)
            counts[metric] = counts.get(metric, 0) + 1
    return {metric: totals[metric] / counts[metric] for metric in totals if counts[metric] > 0}


def _kendall_tau_per_metric(metric_scores: Mapping[str, Mapping[str, float]], ground_truth: Mapping[str, float]) -> Dict[str, float]:
    tau_results: Dict[str, float] = {}
    for metric, scores in metric_scores.items():
        common_models = sorted(set(scores) & set(ground_truth))
        if len(common_models) < 2:
            tau_results[metric] = float("nan")
            continue
        predicted = np.array([scores[model] for model in common_models], dtype=np.float64)
        reference = np.array([ground_truth[model] for model in common_models], dtype=np.float64)
        tau, _ = weightedtau(predicted, reference)
        tau_results[metric] = float(tau)
    return tau_results


def evaluate_single_dataset(
    dataset: str,
    metrics: Sequence[str],
    *,
    gaussian_type: str,
    emms_backend: Optional[str],
    emms_model: Optional[str],
) -> Dict[str, object]:
    if dataset not in DEFAULT_SINGLE_DATASET_MODEL_PATHS:
        raise ValueError(f"Unknown dataset '{dataset}' for single-modality evaluation")
    models = DEFAULT_SINGLE_DATASET_MODEL_PATHS[dataset]
    ground_truth = DEFAULT_SINGLE_GROUND_TRUTH.get(dataset, {})

    raw_results: Dict[str, Dict[str, float]] = {}
    metric_scores: Dict[str, Dict[str, float]] = {}

    for model_name, config in models.items():
        manifest = None
        label_column = "subtype"
        if "msci" in config and isinstance(config["msci"], Mapping):
            manifest = config["msci"].get("manifest")
            label_column = config["msci"].get("label_column", label_column)

        bundle = load_single_features(config["eval"], manifest, label_column)
        model_results = evaluate_metrics(
            bundle,
            metrics,
            gaussian_type=gaussian_type,
            emms_backend=emms_backend,
            emms_model=emms_model,
        )
        raw_results[model_name] = model_results
        _print_results(f"{dataset} :: {model_name}", model_results)

        for metric_name, value in model_results.items():
            metric_scores.setdefault(metric_name, {})[model_name] = float(value)

    tau_scores = _kendall_tau_per_metric(metric_scores, ground_truth)

    if tau_scores:
        print(f"\nKendall tau against ground truth ({dataset}):")
        for metric_name, tau in tau_scores.items():
            print(f"  {metric_name}: {tau}")

    return {
        "models": raw_results,
        "tau": tau_scores,
        "ground_truth": ground_truth,
    }


def evaluate_multimodal_dataset(
    dataset: str,
    metrics: Sequence[str],
    *,
    gaussian_type: str,
    emms_backend: Optional[str],
    emms_model: Optional[str],
    manifest: Optional[str] = None,
    label_column: str = "subtype",
    region_column: str = "patch_id",
    magnification_column: str = "patch_scale",
) -> Dict[str, object]:
    if dataset not in DEFAULT_DATASET_MODEL_PATHS:
        raise ValueError(f"Unknown dataset '{dataset}' for multimodal evaluation")
    models = DEFAULT_DATASET_MODEL_PATHS[dataset]
    ground_truth = DEFAULT_GROUND_TRUTH.get(dataset, {})

    raw_outputs: Dict[str, Dict[str, Dict[str, float]]] = {}
    aggregated_scores: Dict[str, Dict[str, float]] = {}
    metric_scores: Dict[str, Dict[str, float]] = {}

    for model_name, feature_path in models.items():
        image_bundles, text_bundle = load_multimodal_features(
            feature_path,
            manifest,
            label_column=label_column,
            region_column=region_column,
            magnification_column=magnification_column,
        )

        per_outputs: Dict[str, Dict[str, float]] = {}
        for magnification, bundle in image_bundles.items():
            key = f"image_{magnification}x"
            per_outputs[key] = evaluate_metrics(
                bundle,
                metrics,
                gaussian_type=gaussian_type,
                emms_backend=emms_backend,
                emms_model=emms_model,
            )
            _print_results(f"{dataset} :: {model_name} [{key}]", per_outputs[key])

        per_outputs["text"] = evaluate_metrics(
            text_bundle,
            metrics,
            gaussian_type=gaussian_type,
            emms_backend=emms_backend,
            emms_model=emms_model,
        )
        _print_results(f"{dataset} :: {model_name} [text]", per_outputs["text"])

        raw_outputs[model_name] = per_outputs
        aggregated = _aggregate_metric_dict(per_outputs)
        aggregated_scores[model_name] = aggregated
        print(f"\nAggregated metrics for {dataset} :: {model_name}:")
        for metric_name, value in aggregated.items():
            print(f"  {metric_name}: {value}")

        for metric_name, value in aggregated.items():
            metric_scores.setdefault(metric_name, {})[model_name] = float(value)

    tau_scores = _kendall_tau_per_metric(metric_scores, ground_truth)

    if tau_scores:
        print(f"\nKendall tau against ground truth ({dataset}):")
        for metric_name, tau in tau_scores.items():
            print(f"  {metric_name}: {tau}")

    return {
        "models": raw_outputs,
        "aggregated": aggregated_scores,
        "tau": tau_scores,
        "ground_truth": ground_truth,
    }


def _resolve_label_embeddings(label_names: Mapping[int, str], *, backend: Optional[str], model_name: Optional[str]) -> np.ndarray:
    labels = [label_names[idx] for idx in sorted(label_names)]
    backend = backend or "clip"
    if backend == "clip":
        from transformers import CLIPModel, CLIPProcessor

        model_name = model_name or "laion/CLIP-ViT-g-14-laion2B-s12B-b42K"
        model = CLIPModel.from_pretrained(model_name)
        processor = CLIPProcessor.from_pretrained(model_name)
        inputs = processor(text=labels, padding=True, return_tensors="pt")
        with torch.inference_mode():
            text_features = model.get_text_features(**inputs)
        return text_features.cpu().numpy()
    if backend == "gpt2":
        from transformers import GPT2Model, GPT2Tokenizer

        model_name = model_name or "gpt2-medium"
        tokenizer = GPT2Tokenizer.from_pretrained(model_name)
        tokenizer.pad_token = tokenizer.eos_token
        model = GPT2Model.from_pretrained(model_name)
        encoded = tokenizer(labels, return_tensors="pt", padding=True, truncation=True)
        with torch.inference_mode():
            outputs = model(**encoded)
        return outputs.last_hidden_state.mean(dim=1).cpu().numpy()
    if backend == "bert":
        from transformers import AutoTokenizer, BertModel

        model_name = model_name or "bert-large-uncased"
        tokenizer = AutoTokenizer.from_pretrained(model_name)
        model = BertModel.from_pretrained(model_name)
        encoded = tokenizer(labels, return_tensors="pt", padding=True, truncation=True)
        with torch.inference_mode():
            outputs = model(**encoded)
        return outputs.last_hidden_state.mean(dim=1).cpu().numpy()
    raise ValueError(f"Unsupported EMMS backend '{backend}'")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def build_argparser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Compute classical transferability scores on extracted features")
    subparsers = parser.add_subparsers(dest="mode", required=True)

    common = argparse.ArgumentParser(add_help=False)
    common.add_argument(
        "features",
        nargs="?",
        default=None,
        help="Path to the feature .pth file (or omit when using --dataset/--model)",
    )
    common.add_argument("--manifest", type=str, default=None, help="Optional CSV manifest used to recover labels")
    common.add_argument("--label-column", type=str, default="subtype", help="Column containing class labels in the manifest")
    common.add_argument("--metrics", nargs="*", default=["gbc", "sfda", "transrate", "emms", "ncti", "hscore"], help="Metrics to compute")
    common.add_argument("--gaussian-type", choices=["diagonal", "spherical"], default="diagonal", help="Covariance type for GBC")
    common.add_argument("--emms-backend", choices=["clip", "bert", "gpt2"], default="clip", help="Text encoder used for EMMS")
    common.add_argument("--emms-model", type=str, default=None, help="Optional Hugging Face model identifier for EMMS")
    common.add_argument("--json", type=str, default=None, help="Optional output path for JSON results")

    dataset_common = argparse.ArgumentParser(add_help=False)
    dataset_common.add_argument("--metrics", nargs="*", default=["gbc", "sfda", "transrate", "emms", "ncti", "hscore"], help="Metrics to compute")
    dataset_common.add_argument("--gaussian-type", choices=["diagonal", "spherical"], default="diagonal", help="Covariance type for GBC")
    dataset_common.add_argument("--emms-backend", choices=["clip", "bert", "gpt2"], default="clip", help="Text encoder used for EMMS")
    dataset_common.add_argument("--emms-model", type=str, default=None, help="Optional Hugging Face model identifier for EMMS")
    dataset_common.add_argument("--json", type=str, default=None, help="Optional output path for JSON results")

    subparsers.add_parser("single", parents=[common], help="Evaluate single-modality features")

    multi = subparsers.add_parser("multi", parents=[common], help="Evaluate multimodal features")
    multi.add_argument(
        "--dataset",
        type=str,
        default="TCGA",
        choices=sorted(DEFAULT_DATASET_MODEL_PATHS.keys()),
        help="Dataset key providing default feature paths",
    )
    multi.add_argument(
        "--model",
        type=str,
        help="Model name within the dataset mapping when --dataset is used",
    )
    multi.add_argument("--region-column", type=str, default="patch_id", help="Region identifier column in the manifest")
    multi.add_argument("--magnification-column", type=str, default="patch_scale", help="Magnification column in the manifest")

    single_dataset = subparsers.add_parser("single-dataset", parents=[dataset_common], help="Evaluate all single-modality models for a dataset")
    single_dataset.add_argument("--dataset", type=str, default="TCGA", choices=sorted(DEFAULT_SINGLE_DATASET_MODEL_PATHS.keys()), help="Dataset key to evaluate")

    multi_dataset = subparsers.add_parser("multi-dataset", parents=[dataset_common], help="Evaluate all multimodal models for a dataset")
    multi_dataset.add_argument("--dataset", type=str, default="TCGA", choices=sorted(DEFAULT_DATASET_MODEL_PATHS.keys()), help="Dataset key to evaluate")

    return parser


def main(argv: Optional[Sequence[str]] = None) -> Dict[str, object]:
    parser = build_argparser()
    args = parser.parse_args(argv)
    metrics = args.metrics

    if args.mode == "single":
        if args.features is None:
            parser.error("single mode requires a feature file path")
        bundle = load_single_features(args.features, args.manifest, args.label_column)
        result = evaluate_metrics(
            bundle,
            metrics,
            gaussian_type=args.gaussian_type,
            emms_backend=args.emms_backend,
            emms_model=args.emms_model,
        )
        _print_results(args.features, result)
        if args.json:
            _write_json(args.json, {args.features: result})
        return result

    if args.mode == "single-dataset":
        results = evaluate_single_dataset(
            args.dataset,
            metrics,
            gaussian_type=args.gaussian_type,
            emms_backend=args.emms_backend,
            emms_model=args.emms_model,
        )
        if args.json:
            _write_json(args.json, results)
        return results

    if args.mode == "multi-dataset":
        results = evaluate_multimodal_dataset(
            args.dataset,
            metrics,
            gaussian_type=args.gaussian_type,
            emms_backend=args.emms_backend,
            emms_model=args.emms_model,
        )
        if args.json:
            _write_json(args.json, results)
        return results

    feature_path = args.features
    if feature_path is None:
        dataset_key = args.dataset or "TCGA"
        dataset_paths = DEFAULT_DATASET_MODEL_PATHS.get(dataset_key)
        if dataset_paths is None:
            parser.error(f"Unknown dataset '{dataset_key}'")
        if args.model:
            if args.model not in dataset_paths:
                parser.error(f"Model '{args.model}' not found in dataset '{dataset_key}'")
            feature_path = dataset_paths[args.model]
        else:
            results = evaluate_multimodal_dataset(
                dataset_key,
                metrics,
                gaussian_type=args.gaussian_type,
                emms_backend=args.emms_backend,
                emms_model=args.emms_model,
                manifest=args.manifest,
                label_column=args.label_column,
                region_column=args.region_column,
                magnification_column=args.magnification_column,
            )
            if args.json:
                _write_json(args.json, results)
            return results

    image_bundles, text_bundle = load_multimodal_features(
        feature_path,
        args.manifest,
        label_column=args.label_column,
        region_column=args.region_column,
        magnification_column=args.magnification_column,
    )
    aggregated: Dict[str, object] = {}
    for magnification, bundle in image_bundles.items():
        key = f"image_{magnification}x"
        aggregated[key] = evaluate_metrics(
            bundle,
            metrics,
            gaussian_type=args.gaussian_type,
            emms_backend=args.emms_backend,
            emms_model=args.emms_model,
        )
        _print_results(f"{feature_path} [image {magnification}x]", aggregated[key])
    aggregated["text"] = evaluate_metrics(
        text_bundle,
        metrics,
        gaussian_type=args.gaussian_type,
        emms_backend=args.emms_backend,
        emms_model=args.emms_model,
    )
    _print_results(f"{feature_path} [text]", aggregated["text"])
    if args.json:
        _write_json(args.json, aggregated)
    return aggregated


def _print_results(name: str, results: Mapping[str, object]) -> None:
    print(f"\n=== Results for {name} ===")
    if not results:
        print("No metrics were computed (likely due to missing labels)")
        return
    for metric, value in results.items():
        print(f"{metric}: {value}")


def _write_json(path: str, payload: Mapping[str, object]) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)
    print(f"Results written to {path}")


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    main()
